---
baseUrl: jem.vibing.digital
title: Jan Emily M
# headline: what's the vibe?
links:
   - 
      image: https://res.cloudinary.com/foundations-design/image/upload/v1693520390/sm-icons/instagram.svg
      url: janemilym.com
titleColor: "#000853"
headlineColor: "#FFFFFF"
backgroundImage: "/anime.png"
---
